name: Waqar Saleem
description: Waqar Saleem's site
url: "https://waqarsaleem.github.io"
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: GFM
math_engine: mathjax
syntax_highlighter: rouge